# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""Base indexer interface for SKLT sparse attention."""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any

import torch

from vllm.config.attention import IndexerConfig


@dataclass
class SparsityInfo:
    """Container for sparsity information.
    
    Attributes:
        sparse_len: (B, queries, num_query_heads, 1) - number of valid keys per query head
        sparse_idx: (B, queries, num_query_heads, max_sparse_k) - indices of sparse keys
        sparse_weights: (B, queries, num_query_heads, max_sparse_k) - attention weights
    """
    sparse_len: torch.Tensor
    sparse_idx: torch.Tensor
    sparse_weights: torch.Tensor
    
    def validate_shapes(self):
        """Ensure all tensors have compatible shapes."""
        B, Q, H, one = self.sparse_len.shape
        assert one == 1, f"sparse_len last dim should be 1, got {one}"
        
        max_k = self.sparse_idx.shape[-1]
        assert self.sparse_idx.shape == (B, Q, H, max_k), (
            f"sparse_idx shape mismatch: expected {(B, Q, H, max_k)}, "
            f"got {self.sparse_idx.shape}"
        )
        assert self.sparse_weights.shape == (B, Q, H, max_k), (
            f"sparse_weights shape mismatch: expected {(B, Q, H, max_k)}, "
            f"got {self.sparse_weights.shape}"
        )


class BaseIndexer(ABC):
    """Base class for sparse attention indexers.
    
    Indexers are responsible for computing sparsity patterns (which keys
    each query attends to) and optional weights for weighted attention.
    """
    
    def __init__(self, indexer_config: IndexerConfig, device: torch.device):
        """Initialize indexer.
        
        Args:
            indexer_config: Configuration for the indexer
            device: Device to allocate buffers on
        """
        self.config = indexer_config
        self.device = device
        # Pre-allocate buffers for CUDA graph compatibility
        self._init_buffers()
    
    @abstractmethod
    def _init_buffers(self):
        """Initialize reusable buffers for CUDA graph compatibility.
        
        Buffers should be allocated at maximum size based on config
        and scheduler limits. Actual usage will slice these buffers.
        """
        pass
    
    @abstractmethod
    def compute_sparsity(
        self,
        batch_size: int,
        num_queries: int,
        num_query_heads: int,
        num_kv_heads: int,
        seq_lens: torch.Tensor,  # (B,) current sequence lengths
        query_start_loc: torch.Tensor,  # (B+1,) query positions
        attn_metadata: Any,  # Backend-specific metadata
    ) -> SparsityInfo:
        """Compute sparse attention indices and weights.
        
        Args:
            batch_size: Number of sequences in batch
            num_queries: Total number of query tokens across batch
            num_query_heads: Number of query attention heads
            num_kv_heads: Number of key/value heads (for GQA)
            seq_lens: Sequence lengths for each request in batch
            query_start_loc: Starting position of queries for each request
            attn_metadata: Additional metadata (backend-specific)
            
        Returns:
            SparsityInfo with populated buffers (sliced views of pre-allocated buffers)
        """
        pass
    
    @abstractmethod
    def get_max_sparse_k(self) -> int:
        """Return maximum number of sparse keys per head.
        
        Returns:
            Maximum sparse keys that could be generated by this indexer
        """
        pass
